save_dir: resnet_v1_eembc

model:
  name: resnet_v1_eembc
  filters: 
  - 16
  - 16
  - 32
  - 32
  - 64
  - 64
  l1: 0
  l2: 1e-4
  kernels:
  - 3
  - 3
  - 3
  - 3
  - 3
  - 1
  - 3
  - 3
  - 1
  strides: 
  - '111'
  - '212'
  - '212'


pruning:
  sparsity: 1.0 

fit:
  compile:
    initial_lr: 0.001
    lr_decay: 0.99
    optimizer: Adam
    loss: categorical_crossentropy
  epochs: 200
  patience: 40
  batch_size: 32
  verbose: 1

convert:
  OutputDir: my-hls-test
  XilinxPart: xc7z020clg400-1
  Backend: Vivado
  IOType: io_stream
  Precision: ap_fixed<8,4>
  ReuseFactor: 2304
  Strategy: Resource