save_dir: resnet_v1_eembc_tiny

model:
  name: resnet_v1_eembc
  filters: 
  - 32
  - 32
  l1: 0
  l2: 1e-4
  kernels:
  - 3
  - 3
  - 3
  strides:
  - '311'

pruning:
  sparsity: 1.0 

fit:
  compile:
    initial_lr: 0.001
    lr_decay: 0.99
    optimizer: Adam
    loss: categorical_crossentropy
  epochs: 200
  patience: 40
  batch_size: 32
  verbose: 1

convert:
  OutputDir: my-hls-test-tiny
  XilinxPart: xc7z020clg400-1
  Backend: Pynq
  IOType: io_stream
  Precision: ap_fixed<10,6,AP_SAT,AP_RND>
  PrecisionActivation: ap_fixed<10,6,AP_SAT,AP_RND>
  PrecisionAccumulator: ap_fixed<14,10,AP_RND,AP_SAT>
  ReuseFactor: 1024
  ClockPeriod: 20
  Strategy: Resource
