-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity relu_array_array_ap_fixed_4u_relu_config7_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    data_V_data_0_V_dout : IN STD_LOGIC_VECTOR (8 downto 0);
    data_V_data_0_V_empty_n : IN STD_LOGIC;
    data_V_data_0_V_read : OUT STD_LOGIC;
    data_V_data_1_V_dout : IN STD_LOGIC_VECTOR (8 downto 0);
    data_V_data_1_V_empty_n : IN STD_LOGIC;
    data_V_data_1_V_read : OUT STD_LOGIC;
    data_V_data_2_V_dout : IN STD_LOGIC_VECTOR (8 downto 0);
    data_V_data_2_V_empty_n : IN STD_LOGIC;
    data_V_data_2_V_read : OUT STD_LOGIC;
    data_V_data_3_V_dout : IN STD_LOGIC_VECTOR (8 downto 0);
    data_V_data_3_V_empty_n : IN STD_LOGIC;
    data_V_data_3_V_read : OUT STD_LOGIC;
    res_V_data_0_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    res_V_data_0_V_full_n : IN STD_LOGIC;
    res_V_data_0_V_write : OUT STD_LOGIC;
    res_V_data_1_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    res_V_data_1_V_full_n : IN STD_LOGIC;
    res_V_data_1_V_write : OUT STD_LOGIC;
    res_V_data_2_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    res_V_data_2_V_full_n : IN STD_LOGIC;
    res_V_data_2_V_write : OUT STD_LOGIC;
    res_V_data_3_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    res_V_data_3_V_full_n : IN STD_LOGIC;
    res_V_data_3_V_write : OUT STD_LOGIC );
end;


architecture behav of relu_array_array_ap_fixed_4u_relu_config7_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv11_400 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv7_7F : STD_LOGIC_VECTOR (6 downto 0) := "1111111";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";

    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal data_V_data_0_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln60_reg_419 : STD_LOGIC_VECTOR (0 downto 0);
    signal data_V_data_1_V_blk_n : STD_LOGIC;
    signal data_V_data_2_V_blk_n : STD_LOGIC;
    signal data_V_data_3_V_blk_n : STD_LOGIC;
    signal res_V_data_0_V_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal icmp_ln60_reg_419_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal res_V_data_1_V_blk_n : STD_LOGIC;
    signal res_V_data_2_V_blk_n : STD_LOGIC;
    signal res_V_data_3_V_blk_n : STD_LOGIC;
    signal i_0_reg_108 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln60_fu_119_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal io_acc_block_signal_op20 : STD_LOGIC;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal io_acc_block_signal_op68 : STD_LOGIC;
    signal ap_block_state4_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal i_fu_125_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal tmp_data_0_V_1_fu_203_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_data_0_V_1_reg_428 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_data_1_V_1_fu_267_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_data_1_V_1_reg_433 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_data_2_V_1_fu_331_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_data_2_V_1_reg_438 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_data_3_V_1_fu_395_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_data_3_V_1_reg_443 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state2 : STD_LOGIC;
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal trunc_ln746_fu_153_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_Result_2_fu_173_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_1_fu_165_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln785_fu_183_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln785_fu_189_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln_fu_157_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln1494_fu_147_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln785_fu_195_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln746_4_fu_217_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_Result_2_1_fu_237_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_2_fu_229_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln785_1_fu_247_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln785_1_fu_253_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln746_1_fu_221_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln1494_1_fu_211_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln785_1_fu_259_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln746_5_fu_281_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_Result_2_2_fu_301_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_3_fu_293_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln785_2_fu_311_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln785_2_fu_317_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln746_2_fu_285_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln1494_2_fu_275_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln785_2_fu_323_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln746_6_fu_345_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_Result_2_3_fu_365_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_4_fu_357_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln785_3_fu_375_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln785_3_fu_381_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln746_3_fu_349_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln1494_3_fu_339_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln785_3_fu_387_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then
                    if ((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2)) then 
                        ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state2);
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                elsif ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_0_reg_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln60_fu_119_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                i_0_reg_108 <= i_fu_125_p2;
            elsif ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_0_reg_108 <= ap_const_lv11_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln60_reg_419 <= icmp_ln60_fu_119_p2;
                icmp_ln60_reg_419_pp0_iter1_reg <= icmp_ln60_reg_419;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln60_reg_419 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_data_0_V_1_reg_428 <= tmp_data_0_V_1_fu_203_p3;
                tmp_data_1_V_1_reg_433 <= tmp_data_1_V_1_fu_267_p3;
                tmp_data_2_V_1_reg_438 <= tmp_data_2_V_1_fu_331_p3;
                tmp_data_3_V_1_reg_443 <= tmp_data_3_V_1_fu_395_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, icmp_ln60_fu_119_p2, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln60_fu_119_p2 = ap_const_lv1_1))) and not(((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln60_fu_119_p2 = ap_const_lv1_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state5 <= ap_CS_fsm(2);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln60_reg_419, ap_enable_reg_pp0_iter2, icmp_ln60_reg_419_pp0_iter1_reg, io_acc_block_signal_op20, io_acc_block_signal_op68)
    begin
                ap_block_pp0_stage0_01001 <= (((icmp_ln60_reg_419_pp0_iter1_reg = ap_const_lv1_0) and (io_acc_block_signal_op68 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((icmp_ln60_reg_419 = ap_const_lv1_0) and (io_acc_block_signal_op20 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln60_reg_419, ap_enable_reg_pp0_iter2, icmp_ln60_reg_419_pp0_iter1_reg, io_acc_block_signal_op20, io_acc_block_signal_op68)
    begin
                ap_block_pp0_stage0_11001 <= (((icmp_ln60_reg_419_pp0_iter1_reg = ap_const_lv1_0) and (io_acc_block_signal_op68 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((icmp_ln60_reg_419 = ap_const_lv1_0) and (io_acc_block_signal_op20 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln60_reg_419, ap_enable_reg_pp0_iter2, icmp_ln60_reg_419_pp0_iter1_reg, io_acc_block_signal_op20, io_acc_block_signal_op68)
    begin
                ap_block_pp0_stage0_subdone <= (((icmp_ln60_reg_419_pp0_iter1_reg = ap_const_lv1_0) and (io_acc_block_signal_op68 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((icmp_ln60_reg_419 = ap_const_lv1_0) and (io_acc_block_signal_op20 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;

        ap_block_state2_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state3_pp0_stage0_iter1_assign_proc : process(icmp_ln60_reg_419, io_acc_block_signal_op20)
    begin
                ap_block_state3_pp0_stage0_iter1 <= ((icmp_ln60_reg_419 = ap_const_lv1_0) and (io_acc_block_signal_op20 = ap_const_logic_0));
    end process;


    ap_block_state4_pp0_stage0_iter2_assign_proc : process(icmp_ln60_reg_419_pp0_iter1_reg, io_acc_block_signal_op68)
    begin
                ap_block_state4_pp0_stage0_iter2 <= ((icmp_ln60_reg_419_pp0_iter1_reg = ap_const_lv1_0) and (io_acc_block_signal_op68 = ap_const_logic_0));
    end process;


    ap_condition_pp0_exit_iter0_state2_assign_proc : process(icmp_ln60_fu_119_p2)
    begin
        if ((icmp_ln60_fu_119_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;

    data_V_data_0_V_blk_n_assign_proc : process(data_V_data_0_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln60_reg_419)
    begin
        if (((icmp_ln60_reg_419 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            data_V_data_0_V_blk_n <= data_V_data_0_V_empty_n;
        else 
            data_V_data_0_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_V_data_0_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln60_reg_419, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln60_reg_419 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            data_V_data_0_V_read <= ap_const_logic_1;
        else 
            data_V_data_0_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_V_data_1_V_blk_n_assign_proc : process(data_V_data_1_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln60_reg_419)
    begin
        if (((icmp_ln60_reg_419 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            data_V_data_1_V_blk_n <= data_V_data_1_V_empty_n;
        else 
            data_V_data_1_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_V_data_1_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln60_reg_419, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln60_reg_419 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            data_V_data_1_V_read <= ap_const_logic_1;
        else 
            data_V_data_1_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_V_data_2_V_blk_n_assign_proc : process(data_V_data_2_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln60_reg_419)
    begin
        if (((icmp_ln60_reg_419 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            data_V_data_2_V_blk_n <= data_V_data_2_V_empty_n;
        else 
            data_V_data_2_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_V_data_2_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln60_reg_419, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln60_reg_419 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            data_V_data_2_V_read <= ap_const_logic_1;
        else 
            data_V_data_2_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_V_data_3_V_blk_n_assign_proc : process(data_V_data_3_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln60_reg_419)
    begin
        if (((icmp_ln60_reg_419 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            data_V_data_3_V_blk_n <= data_V_data_3_V_empty_n;
        else 
            data_V_data_3_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_V_data_3_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln60_reg_419, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln60_reg_419 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            data_V_data_3_V_read <= ap_const_logic_1;
        else 
            data_V_data_3_V_read <= ap_const_logic_0;
        end if; 
    end process;

    i_fu_125_p2 <= std_logic_vector(unsigned(i_0_reg_108) + unsigned(ap_const_lv11_1));
    icmp_ln1494_1_fu_211_p2 <= "1" when (signed(data_V_data_1_V_dout) > signed(ap_const_lv9_0)) else "0";
    icmp_ln1494_2_fu_275_p2 <= "1" when (signed(data_V_data_2_V_dout) > signed(ap_const_lv9_0)) else "0";
    icmp_ln1494_3_fu_339_p2 <= "1" when (signed(data_V_data_3_V_dout) > signed(ap_const_lv9_0)) else "0";
    icmp_ln1494_fu_147_p2 <= "1" when (signed(data_V_data_0_V_dout) > signed(ap_const_lv9_0)) else "0";
    icmp_ln60_fu_119_p2 <= "1" when (i_0_reg_108 = ap_const_lv11_400) else "0";
    icmp_ln785_1_fu_247_p2 <= "0" when (p_Result_2_1_fu_237_p4 = ap_const_lv3_0) else "1";
    icmp_ln785_2_fu_311_p2 <= "0" when (p_Result_2_2_fu_301_p4 = ap_const_lv3_0) else "1";
    icmp_ln785_3_fu_375_p2 <= "0" when (p_Result_2_3_fu_365_p4 = ap_const_lv3_0) else "1";
    icmp_ln785_fu_183_p2 <= "0" when (p_Result_2_fu_173_p4 = ap_const_lv3_0) else "1";

    internal_ap_ready_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    io_acc_block_signal_op20 <= (data_V_data_3_V_empty_n and data_V_data_2_V_empty_n and data_V_data_1_V_empty_n and data_V_data_0_V_empty_n);
    io_acc_block_signal_op68 <= (res_V_data_3_V_full_n and res_V_data_2_V_full_n and res_V_data_1_V_full_n and res_V_data_0_V_full_n);
    or_ln785_1_fu_253_p2 <= (tmp_2_fu_229_p3 or icmp_ln785_1_fu_247_p2);
    or_ln785_2_fu_317_p2 <= (tmp_3_fu_293_p3 or icmp_ln785_2_fu_311_p2);
    or_ln785_3_fu_381_p2 <= (tmp_4_fu_357_p3 or icmp_ln785_3_fu_375_p2);
    or_ln785_fu_189_p2 <= (tmp_1_fu_165_p3 or icmp_ln785_fu_183_p2);
    p_Result_2_1_fu_237_p4 <= data_V_data_1_V_dout(8 downto 6);
    p_Result_2_2_fu_301_p4 <= data_V_data_2_V_dout(8 downto 6);
    p_Result_2_3_fu_365_p4 <= data_V_data_3_V_dout(8 downto 6);
    p_Result_2_fu_173_p4 <= data_V_data_0_V_dout(8 downto 6);

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;


    res_V_data_0_V_blk_n_assign_proc : process(res_V_data_0_V_full_n, ap_block_pp0_stage0, ap_enable_reg_pp0_iter2, icmp_ln60_reg_419_pp0_iter1_reg)
    begin
        if (((icmp_ln60_reg_419_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            res_V_data_0_V_blk_n <= res_V_data_0_V_full_n;
        else 
            res_V_data_0_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_V_data_0_V_din <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_data_0_V_1_reg_428),8));

    res_V_data_0_V_write_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln60_reg_419_pp0_iter1_reg, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln60_reg_419_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            res_V_data_0_V_write <= ap_const_logic_1;
        else 
            res_V_data_0_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_1_V_blk_n_assign_proc : process(res_V_data_1_V_full_n, ap_block_pp0_stage0, ap_enable_reg_pp0_iter2, icmp_ln60_reg_419_pp0_iter1_reg)
    begin
        if (((icmp_ln60_reg_419_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            res_V_data_1_V_blk_n <= res_V_data_1_V_full_n;
        else 
            res_V_data_1_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_V_data_1_V_din <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_data_1_V_1_reg_433),8));

    res_V_data_1_V_write_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln60_reg_419_pp0_iter1_reg, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln60_reg_419_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            res_V_data_1_V_write <= ap_const_logic_1;
        else 
            res_V_data_1_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_2_V_blk_n_assign_proc : process(res_V_data_2_V_full_n, ap_block_pp0_stage0, ap_enable_reg_pp0_iter2, icmp_ln60_reg_419_pp0_iter1_reg)
    begin
        if (((icmp_ln60_reg_419_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            res_V_data_2_V_blk_n <= res_V_data_2_V_full_n;
        else 
            res_V_data_2_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_V_data_2_V_din <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_data_2_V_1_reg_438),8));

    res_V_data_2_V_write_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln60_reg_419_pp0_iter1_reg, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln60_reg_419_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            res_V_data_2_V_write <= ap_const_logic_1;
        else 
            res_V_data_2_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_3_V_blk_n_assign_proc : process(res_V_data_3_V_full_n, ap_block_pp0_stage0, ap_enable_reg_pp0_iter2, icmp_ln60_reg_419_pp0_iter1_reg)
    begin
        if (((icmp_ln60_reg_419_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            res_V_data_3_V_blk_n <= res_V_data_3_V_full_n;
        else 
            res_V_data_3_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_V_data_3_V_din <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_data_3_V_1_reg_443),8));

    res_V_data_3_V_write_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln60_reg_419_pp0_iter1_reg, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln60_reg_419_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            res_V_data_3_V_write <= ap_const_logic_1;
        else 
            res_V_data_3_V_write <= ap_const_logic_0;
        end if; 
    end process;

    select_ln785_1_fu_259_p3 <= 
        ap_const_lv7_7F when (or_ln785_1_fu_253_p2(0) = '1') else 
        trunc_ln746_1_fu_221_p3;
    select_ln785_2_fu_323_p3 <= 
        ap_const_lv7_7F when (or_ln785_2_fu_317_p2(0) = '1') else 
        trunc_ln746_2_fu_285_p3;
    select_ln785_3_fu_387_p3 <= 
        ap_const_lv7_7F when (or_ln785_3_fu_381_p2(0) = '1') else 
        trunc_ln746_3_fu_349_p3;
    select_ln785_fu_195_p3 <= 
        ap_const_lv7_7F when (or_ln785_fu_189_p2(0) = '1') else 
        trunc_ln_fu_157_p3;
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    tmp_1_fu_165_p3 <= data_V_data_0_V_dout(5 downto 5);
    tmp_2_fu_229_p3 <= data_V_data_1_V_dout(5 downto 5);
    tmp_3_fu_293_p3 <= data_V_data_2_V_dout(5 downto 5);
    tmp_4_fu_357_p3 <= data_V_data_3_V_dout(5 downto 5);
    tmp_data_0_V_1_fu_203_p3 <= 
        select_ln785_fu_195_p3 when (icmp_ln1494_fu_147_p2(0) = '1') else 
        ap_const_lv7_0;
    tmp_data_1_V_1_fu_267_p3 <= 
        select_ln785_1_fu_259_p3 when (icmp_ln1494_1_fu_211_p2(0) = '1') else 
        ap_const_lv7_0;
    tmp_data_2_V_1_fu_331_p3 <= 
        select_ln785_2_fu_323_p3 when (icmp_ln1494_2_fu_275_p2(0) = '1') else 
        ap_const_lv7_0;
    tmp_data_3_V_1_fu_395_p3 <= 
        select_ln785_3_fu_387_p3 when (icmp_ln1494_3_fu_339_p2(0) = '1') else 
        ap_const_lv7_0;
    trunc_ln746_1_fu_221_p3 <= (trunc_ln746_4_fu_217_p1 & ap_const_lv2_0);
    trunc_ln746_2_fu_285_p3 <= (trunc_ln746_5_fu_281_p1 & ap_const_lv2_0);
    trunc_ln746_3_fu_349_p3 <= (trunc_ln746_6_fu_345_p1 & ap_const_lv2_0);
    trunc_ln746_4_fu_217_p1 <= data_V_data_1_V_dout(5 - 1 downto 0);
    trunc_ln746_5_fu_281_p1 <= data_V_data_2_V_dout(5 - 1 downto 0);
    trunc_ln746_6_fu_345_p1 <= data_V_data_3_V_dout(5 - 1 downto 0);
    trunc_ln746_fu_153_p1 <= data_V_data_0_V_dout(5 - 1 downto 0);
    trunc_ln_fu_157_p3 <= (trunc_ln746_fu_153_p1 & ap_const_lv2_0);
end behav;
