-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity zeropad2d_cl_array_array_ap_fixed_4u_config21_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    data_V_data_0_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    data_V_data_0_V_empty_n : IN STD_LOGIC;
    data_V_data_0_V_read : OUT STD_LOGIC;
    data_V_data_1_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    data_V_data_1_V_empty_n : IN STD_LOGIC;
    data_V_data_1_V_read : OUT STD_LOGIC;
    data_V_data_2_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    data_V_data_2_V_empty_n : IN STD_LOGIC;
    data_V_data_2_V_read : OUT STD_LOGIC;
    data_V_data_3_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    data_V_data_3_V_empty_n : IN STD_LOGIC;
    data_V_data_3_V_read : OUT STD_LOGIC;
    res_V_data_0_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    res_V_data_0_V_full_n : IN STD_LOGIC;
    res_V_data_0_V_write : OUT STD_LOGIC;
    res_V_data_1_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    res_V_data_1_V_full_n : IN STD_LOGIC;
    res_V_data_1_V_write : OUT STD_LOGIC;
    res_V_data_2_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    res_V_data_2_V_full_n : IN STD_LOGIC;
    res_V_data_2_V_write : OUT STD_LOGIC;
    res_V_data_3_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    res_V_data_3_V_full_n : IN STD_LOGIC;
    res_V_data_3_V_write : OUT STD_LOGIC );
end;


architecture behav of zeropad2d_cl_array_array_ap_fixed_4u_config21_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (6 downto 0) := "0010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (6 downto 0) := "0100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv6_23 : STD_LOGIC_VECTOR (5 downto 0) := "100011";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal data_V_data_0_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal icmp_ln65_fu_200_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal data_V_data_1_V_blk_n : STD_LOGIC;
    signal data_V_data_2_V_blk_n : STD_LOGIC;
    signal data_V_data_3_V_blk_n : STD_LOGIC;
    signal res_V_data_0_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln56_fu_176_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal icmp_ln61_fu_188_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal icmp_ln68_fu_232_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal icmp_ln74_fu_256_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal res_V_data_1_V_blk_n : STD_LOGIC;
    signal res_V_data_2_V_blk_n : STD_LOGIC;
    signal res_V_data_3_V_blk_n : STD_LOGIC;
    signal j_fu_182_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal io_acc_block_signal_op25 : STD_LOGIC;
    signal ap_block_state2 : BOOLEAN;
    signal i_1_fu_194_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal i_1_reg_279 : STD_LOGIC_VECTOR (5 downto 0);
    signal io_acc_block_signal_op37 : STD_LOGIC;
    signal ap_block_state3 : BOOLEAN;
    signal j_1_fu_206_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal io_acc_block_signal_op46 : STD_LOGIC;
    signal io_acc_block_signal_op51 : STD_LOGIC;
    signal ap_block_state4 : BOOLEAN;
    signal j_3_fu_238_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal io_acc_block_signal_op60 : STD_LOGIC;
    signal ap_block_state5 : BOOLEAN;
    signal i_fu_250_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal i_reg_303 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal j_2_fu_262_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal io_acc_block_signal_op79 : STD_LOGIC;
    signal ap_block_state7 : BOOLEAN;
    signal j_0_reg_110 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal i1_0_reg_121 : STD_LOGIC_VECTOR (5 downto 0);
    signal j3_0_reg_132 : STD_LOGIC_VECTOR (5 downto 0);
    signal j4_0_reg_143 : STD_LOGIC_VECTOR (1 downto 0);
    signal i5_0_reg_154 : STD_LOGIC_VECTOR (1 downto 0);
    signal j6_0_reg_165 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln73_fu_244_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (6 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln73_fu_244_p2 = ap_const_lv1_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i1_0_reg_121_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((icmp_ln56_fu_176_p2 = ap_const_lv1_0) and (io_acc_block_signal_op25 = ap_const_logic_0))) and (icmp_ln56_fu_176_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                i1_0_reg_121 <= ap_const_lv6_0;
            elsif ((not(((icmp_ln68_fu_232_p2 = ap_const_lv1_0) and (io_acc_block_signal_op60 = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln68_fu_232_p2 = ap_const_lv1_1))) then 
                i1_0_reg_121 <= i_1_reg_279;
            end if; 
        end if;
    end process;

    i5_0_reg_154_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((icmp_ln61_fu_188_p2 = ap_const_lv1_0) and (io_acc_block_signal_op37 = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln61_fu_188_p2 = ap_const_lv1_1))) then 
                i5_0_reg_154 <= ap_const_lv2_0;
            elsif ((not(((icmp_ln74_fu_256_p2 = ap_const_lv1_0) and (io_acc_block_signal_op79 = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln74_fu_256_p2 = ap_const_lv1_1))) then 
                i5_0_reg_154 <= i_reg_303;
            end if; 
        end if;
    end process;

    j3_0_reg_132_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((icmp_ln61_fu_188_p2 = ap_const_lv1_0) and (io_acc_block_signal_op37 = ap_const_logic_0))) and (icmp_ln61_fu_188_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                j3_0_reg_132 <= ap_const_lv6_0;
            elsif ((not((((icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (io_acc_block_signal_op51 = ap_const_logic_0)) or ((icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (io_acc_block_signal_op46 = ap_const_logic_0)))) and (icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                j3_0_reg_132 <= j_1_fu_206_p2;
            end if; 
        end if;
    end process;

    j4_0_reg_143_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((((icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (io_acc_block_signal_op51 = ap_const_logic_0)) or ((icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (io_acc_block_signal_op46 = ap_const_logic_0)))) and (icmp_ln65_fu_200_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                j4_0_reg_143 <= ap_const_lv2_0;
            elsif ((not(((icmp_ln68_fu_232_p2 = ap_const_lv1_0) and (io_acc_block_signal_op60 = ap_const_logic_0))) and (icmp_ln68_fu_232_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                j4_0_reg_143 <= j_3_fu_238_p2;
            end if; 
        end if;
    end process;

    j6_0_reg_165_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((icmp_ln74_fu_256_p2 = ap_const_lv1_0) and (io_acc_block_signal_op79 = ap_const_logic_0))) and (icmp_ln74_fu_256_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                j6_0_reg_165 <= j_2_fu_262_p2;
            elsif (((icmp_ln73_fu_244_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                j6_0_reg_165 <= ap_const_lv6_0;
            end if; 
        end if;
    end process;

    j_0_reg_110_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((icmp_ln56_fu_176_p2 = ap_const_lv1_0) and (io_acc_block_signal_op25 = ap_const_logic_0))) and (icmp_ln56_fu_176_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                j_0_reg_110 <= j_fu_182_p2;
            elsif ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                j_0_reg_110 <= ap_const_lv6_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((icmp_ln61_fu_188_p2 = ap_const_lv1_0) and (io_acc_block_signal_op37 = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                i_1_reg_279 <= i_1_fu_194_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                i_reg_303 <= i_fu_250_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state4, icmp_ln65_fu_200_p2, ap_CS_fsm_state2, icmp_ln56_fu_176_p2, ap_CS_fsm_state3, icmp_ln61_fu_188_p2, ap_CS_fsm_state5, icmp_ln68_fu_232_p2, ap_CS_fsm_state7, icmp_ln74_fu_256_p2, io_acc_block_signal_op25, io_acc_block_signal_op37, io_acc_block_signal_op46, io_acc_block_signal_op51, io_acc_block_signal_op60, ap_CS_fsm_state6, io_acc_block_signal_op79, icmp_ln73_fu_244_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if ((not(((icmp_ln56_fu_176_p2 = ap_const_lv1_0) and (io_acc_block_signal_op25 = ap_const_logic_0))) and (icmp_ln56_fu_176_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                elsif ((not(((icmp_ln56_fu_176_p2 = ap_const_lv1_0) and (io_acc_block_signal_op25 = ap_const_logic_0))) and (icmp_ln56_fu_176_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if ((not(((icmp_ln61_fu_188_p2 = ap_const_lv1_0) and (io_acc_block_signal_op37 = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln61_fu_188_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                elsif ((not(((icmp_ln61_fu_188_p2 = ap_const_lv1_0) and (io_acc_block_signal_op37 = ap_const_logic_0))) and (icmp_ln61_fu_188_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if ((not((((icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (io_acc_block_signal_op51 = ap_const_logic_0)) or ((icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (io_acc_block_signal_op46 = ap_const_logic_0)))) and (icmp_ln65_fu_200_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                elsif ((not((((icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (io_acc_block_signal_op51 = ap_const_logic_0)) or ((icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (io_acc_block_signal_op46 = ap_const_logic_0)))) and (icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if ((not(((icmp_ln68_fu_232_p2 = ap_const_lv1_0) and (io_acc_block_signal_op60 = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln68_fu_232_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                elsif ((not(((icmp_ln68_fu_232_p2 = ap_const_lv1_0) and (io_acc_block_signal_op60 = ap_const_logic_0))) and (icmp_ln68_fu_232_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln73_fu_244_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state7 => 
                if ((not(((icmp_ln74_fu_256_p2 = ap_const_lv1_0) and (io_acc_block_signal_op79 = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln74_fu_256_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                elsif ((not(((icmp_ln74_fu_256_p2 = ap_const_lv1_0) and (io_acc_block_signal_op79 = ap_const_logic_0))) and (icmp_ln74_fu_256_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);

    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state2_assign_proc : process(icmp_ln56_fu_176_p2, io_acc_block_signal_op25)
    begin
                ap_block_state2 <= ((icmp_ln56_fu_176_p2 = ap_const_lv1_0) and (io_acc_block_signal_op25 = ap_const_logic_0));
    end process;


    ap_block_state3_assign_proc : process(icmp_ln61_fu_188_p2, io_acc_block_signal_op37)
    begin
                ap_block_state3 <= ((icmp_ln61_fu_188_p2 = ap_const_lv1_0) and (io_acc_block_signal_op37 = ap_const_logic_0));
    end process;


    ap_block_state4_assign_proc : process(icmp_ln65_fu_200_p2, io_acc_block_signal_op46, io_acc_block_signal_op51)
    begin
                ap_block_state4 <= (((icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (io_acc_block_signal_op51 = ap_const_logic_0)) or ((icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (io_acc_block_signal_op46 = ap_const_logic_0)));
    end process;


    ap_block_state5_assign_proc : process(icmp_ln68_fu_232_p2, io_acc_block_signal_op60)
    begin
                ap_block_state5 <= ((icmp_ln68_fu_232_p2 = ap_const_lv1_0) and (io_acc_block_signal_op60 = ap_const_logic_0));
    end process;


    ap_block_state7_assign_proc : process(icmp_ln74_fu_256_p2, io_acc_block_signal_op79)
    begin
                ap_block_state7 <= ((icmp_ln74_fu_256_p2 = ap_const_lv1_0) and (io_acc_block_signal_op79 = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state6, icmp_ln73_fu_244_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln73_fu_244_p2 = ap_const_lv1_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;

    data_V_data_0_V_blk_n_assign_proc : process(data_V_data_0_V_empty_n, ap_CS_fsm_state4, icmp_ln65_fu_200_p2)
    begin
        if (((icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            data_V_data_0_V_blk_n <= data_V_data_0_V_empty_n;
        else 
            data_V_data_0_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_V_data_0_V_read_assign_proc : process(ap_CS_fsm_state4, icmp_ln65_fu_200_p2, io_acc_block_signal_op46, io_acc_block_signal_op51)
    begin
        if ((not((((icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (io_acc_block_signal_op51 = ap_const_logic_0)) or ((icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (io_acc_block_signal_op46 = ap_const_logic_0)))) and (icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            data_V_data_0_V_read <= ap_const_logic_1;
        else 
            data_V_data_0_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_V_data_1_V_blk_n_assign_proc : process(data_V_data_1_V_empty_n, ap_CS_fsm_state4, icmp_ln65_fu_200_p2)
    begin
        if (((icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            data_V_data_1_V_blk_n <= data_V_data_1_V_empty_n;
        else 
            data_V_data_1_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_V_data_1_V_read_assign_proc : process(ap_CS_fsm_state4, icmp_ln65_fu_200_p2, io_acc_block_signal_op46, io_acc_block_signal_op51)
    begin
        if ((not((((icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (io_acc_block_signal_op51 = ap_const_logic_0)) or ((icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (io_acc_block_signal_op46 = ap_const_logic_0)))) and (icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            data_V_data_1_V_read <= ap_const_logic_1;
        else 
            data_V_data_1_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_V_data_2_V_blk_n_assign_proc : process(data_V_data_2_V_empty_n, ap_CS_fsm_state4, icmp_ln65_fu_200_p2)
    begin
        if (((icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            data_V_data_2_V_blk_n <= data_V_data_2_V_empty_n;
        else 
            data_V_data_2_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_V_data_2_V_read_assign_proc : process(ap_CS_fsm_state4, icmp_ln65_fu_200_p2, io_acc_block_signal_op46, io_acc_block_signal_op51)
    begin
        if ((not((((icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (io_acc_block_signal_op51 = ap_const_logic_0)) or ((icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (io_acc_block_signal_op46 = ap_const_logic_0)))) and (icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            data_V_data_2_V_read <= ap_const_logic_1;
        else 
            data_V_data_2_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_V_data_3_V_blk_n_assign_proc : process(data_V_data_3_V_empty_n, ap_CS_fsm_state4, icmp_ln65_fu_200_p2)
    begin
        if (((icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            data_V_data_3_V_blk_n <= data_V_data_3_V_empty_n;
        else 
            data_V_data_3_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_V_data_3_V_read_assign_proc : process(ap_CS_fsm_state4, icmp_ln65_fu_200_p2, io_acc_block_signal_op46, io_acc_block_signal_op51)
    begin
        if ((not((((icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (io_acc_block_signal_op51 = ap_const_logic_0)) or ((icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (io_acc_block_signal_op46 = ap_const_logic_0)))) and (icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            data_V_data_3_V_read <= ap_const_logic_1;
        else 
            data_V_data_3_V_read <= ap_const_logic_0;
        end if; 
    end process;

    i_1_fu_194_p2 <= std_logic_vector(unsigned(i1_0_reg_121) + unsigned(ap_const_lv6_1));
    i_fu_250_p2 <= std_logic_vector(unsigned(i5_0_reg_154) + unsigned(ap_const_lv2_1));
    icmp_ln56_fu_176_p2 <= "1" when (j_0_reg_110 = ap_const_lv6_23) else "0";
    icmp_ln61_fu_188_p2 <= "1" when (i1_0_reg_121 = ap_const_lv6_20) else "0";
    icmp_ln65_fu_200_p2 <= "1" when (j3_0_reg_132 = ap_const_lv6_20) else "0";
    icmp_ln68_fu_232_p2 <= "1" when (j4_0_reg_143 = ap_const_lv2_2) else "0";
    icmp_ln73_fu_244_p2 <= "1" when (i5_0_reg_154 = ap_const_lv2_2) else "0";
    icmp_ln74_fu_256_p2 <= "1" when (j6_0_reg_165 = ap_const_lv6_23) else "0";

    internal_ap_ready_assign_proc : process(ap_CS_fsm_state6, icmp_ln73_fu_244_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln73_fu_244_p2 = ap_const_lv1_1))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    io_acc_block_signal_op25 <= (res_V_data_3_V_full_n and res_V_data_2_V_full_n and res_V_data_1_V_full_n and res_V_data_0_V_full_n);
    io_acc_block_signal_op37 <= (res_V_data_3_V_full_n and res_V_data_2_V_full_n and res_V_data_1_V_full_n and res_V_data_0_V_full_n);
    io_acc_block_signal_op46 <= (data_V_data_3_V_empty_n and data_V_data_2_V_empty_n and data_V_data_1_V_empty_n and data_V_data_0_V_empty_n);
    io_acc_block_signal_op51 <= (res_V_data_3_V_full_n and res_V_data_2_V_full_n and res_V_data_1_V_full_n and res_V_data_0_V_full_n);
    io_acc_block_signal_op60 <= (res_V_data_3_V_full_n and res_V_data_2_V_full_n and res_V_data_1_V_full_n and res_V_data_0_V_full_n);
    io_acc_block_signal_op79 <= (res_V_data_3_V_full_n and res_V_data_2_V_full_n and res_V_data_1_V_full_n and res_V_data_0_V_full_n);
    j_1_fu_206_p2 <= std_logic_vector(unsigned(j3_0_reg_132) + unsigned(ap_const_lv6_1));
    j_2_fu_262_p2 <= std_logic_vector(unsigned(j6_0_reg_165) + unsigned(ap_const_lv6_1));
    j_3_fu_238_p2 <= std_logic_vector(unsigned(j4_0_reg_143) + unsigned(ap_const_lv2_1));
    j_fu_182_p2 <= std_logic_vector(unsigned(j_0_reg_110) + unsigned(ap_const_lv6_1));

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;


    res_V_data_0_V_blk_n_assign_proc : process(res_V_data_0_V_full_n, ap_CS_fsm_state4, icmp_ln65_fu_200_p2, ap_CS_fsm_state2, icmp_ln56_fu_176_p2, ap_CS_fsm_state3, icmp_ln61_fu_188_p2, ap_CS_fsm_state5, icmp_ln68_fu_232_p2, ap_CS_fsm_state7, icmp_ln74_fu_256_p2)
    begin
        if ((((icmp_ln56_fu_176_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((icmp_ln74_fu_256_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7)) or ((icmp_ln68_fu_232_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((icmp_ln61_fu_188_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            res_V_data_0_V_blk_n <= res_V_data_0_V_full_n;
        else 
            res_V_data_0_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    res_V_data_0_V_din_assign_proc : process(data_V_data_0_V_dout, ap_CS_fsm_state4, icmp_ln65_fu_200_p2, ap_CS_fsm_state2, icmp_ln56_fu_176_p2, ap_CS_fsm_state3, icmp_ln61_fu_188_p2, ap_CS_fsm_state5, icmp_ln68_fu_232_p2, ap_CS_fsm_state7, icmp_ln74_fu_256_p2, io_acc_block_signal_op25, io_acc_block_signal_op37, io_acc_block_signal_op46, io_acc_block_signal_op51, io_acc_block_signal_op60, io_acc_block_signal_op79)
    begin
        if ((not((((icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (io_acc_block_signal_op51 = ap_const_logic_0)) or ((icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (io_acc_block_signal_op46 = ap_const_logic_0)))) and (icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            res_V_data_0_V_din <= data_V_data_0_V_dout;
        elsif (((not(((icmp_ln56_fu_176_p2 = ap_const_lv1_0) and (io_acc_block_signal_op25 = ap_const_logic_0))) and (icmp_ln56_fu_176_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)) or (not(((icmp_ln74_fu_256_p2 = ap_const_lv1_0) and (io_acc_block_signal_op79 = ap_const_logic_0))) and (icmp_ln74_fu_256_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7)) or (not(((icmp_ln68_fu_232_p2 = ap_const_lv1_0) and (io_acc_block_signal_op60 = ap_const_logic_0))) and (icmp_ln68_fu_232_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5)) or (not(((icmp_ln61_fu_188_p2 = ap_const_lv1_0) and (io_acc_block_signal_op37 = ap_const_logic_0))) and (icmp_ln61_fu_188_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            res_V_data_0_V_din <= ap_const_lv8_0;
        else 
            res_V_data_0_V_din <= "XXXXXXXX";
        end if; 
    end process;


    res_V_data_0_V_write_assign_proc : process(ap_CS_fsm_state4, icmp_ln65_fu_200_p2, ap_CS_fsm_state2, icmp_ln56_fu_176_p2, ap_CS_fsm_state3, icmp_ln61_fu_188_p2, ap_CS_fsm_state5, icmp_ln68_fu_232_p2, ap_CS_fsm_state7, icmp_ln74_fu_256_p2, io_acc_block_signal_op25, io_acc_block_signal_op37, io_acc_block_signal_op46, io_acc_block_signal_op51, io_acc_block_signal_op60, io_acc_block_signal_op79)
    begin
        if (((not(((icmp_ln56_fu_176_p2 = ap_const_lv1_0) and (io_acc_block_signal_op25 = ap_const_logic_0))) and (icmp_ln56_fu_176_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)) or (not((((icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (io_acc_block_signal_op51 = ap_const_logic_0)) or ((icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (io_acc_block_signal_op46 = ap_const_logic_0)))) and (icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4)) or (not(((icmp_ln74_fu_256_p2 = ap_const_lv1_0) and (io_acc_block_signal_op79 = ap_const_logic_0))) and (icmp_ln74_fu_256_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7)) or (not(((icmp_ln68_fu_232_p2 = ap_const_lv1_0) and (io_acc_block_signal_op60 = ap_const_logic_0))) and (icmp_ln68_fu_232_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5)) or (not(((icmp_ln61_fu_188_p2 = ap_const_lv1_0) and (io_acc_block_signal_op37 = ap_const_logic_0))) and (icmp_ln61_fu_188_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            res_V_data_0_V_write <= ap_const_logic_1;
        else 
            res_V_data_0_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_1_V_blk_n_assign_proc : process(res_V_data_1_V_full_n, ap_CS_fsm_state4, icmp_ln65_fu_200_p2, ap_CS_fsm_state2, icmp_ln56_fu_176_p2, ap_CS_fsm_state3, icmp_ln61_fu_188_p2, ap_CS_fsm_state5, icmp_ln68_fu_232_p2, ap_CS_fsm_state7, icmp_ln74_fu_256_p2)
    begin
        if ((((icmp_ln56_fu_176_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((icmp_ln74_fu_256_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7)) or ((icmp_ln68_fu_232_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((icmp_ln61_fu_188_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            res_V_data_1_V_blk_n <= res_V_data_1_V_full_n;
        else 
            res_V_data_1_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    res_V_data_1_V_din_assign_proc : process(data_V_data_1_V_dout, ap_CS_fsm_state4, icmp_ln65_fu_200_p2, ap_CS_fsm_state2, icmp_ln56_fu_176_p2, ap_CS_fsm_state3, icmp_ln61_fu_188_p2, ap_CS_fsm_state5, icmp_ln68_fu_232_p2, ap_CS_fsm_state7, icmp_ln74_fu_256_p2, io_acc_block_signal_op25, io_acc_block_signal_op37, io_acc_block_signal_op46, io_acc_block_signal_op51, io_acc_block_signal_op60, io_acc_block_signal_op79)
    begin
        if ((not((((icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (io_acc_block_signal_op51 = ap_const_logic_0)) or ((icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (io_acc_block_signal_op46 = ap_const_logic_0)))) and (icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            res_V_data_1_V_din <= data_V_data_1_V_dout;
        elsif (((not(((icmp_ln56_fu_176_p2 = ap_const_lv1_0) and (io_acc_block_signal_op25 = ap_const_logic_0))) and (icmp_ln56_fu_176_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)) or (not(((icmp_ln74_fu_256_p2 = ap_const_lv1_0) and (io_acc_block_signal_op79 = ap_const_logic_0))) and (icmp_ln74_fu_256_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7)) or (not(((icmp_ln68_fu_232_p2 = ap_const_lv1_0) and (io_acc_block_signal_op60 = ap_const_logic_0))) and (icmp_ln68_fu_232_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5)) or (not(((icmp_ln61_fu_188_p2 = ap_const_lv1_0) and (io_acc_block_signal_op37 = ap_const_logic_0))) and (icmp_ln61_fu_188_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            res_V_data_1_V_din <= ap_const_lv8_0;
        else 
            res_V_data_1_V_din <= "XXXXXXXX";
        end if; 
    end process;


    res_V_data_1_V_write_assign_proc : process(ap_CS_fsm_state4, icmp_ln65_fu_200_p2, ap_CS_fsm_state2, icmp_ln56_fu_176_p2, ap_CS_fsm_state3, icmp_ln61_fu_188_p2, ap_CS_fsm_state5, icmp_ln68_fu_232_p2, ap_CS_fsm_state7, icmp_ln74_fu_256_p2, io_acc_block_signal_op25, io_acc_block_signal_op37, io_acc_block_signal_op46, io_acc_block_signal_op51, io_acc_block_signal_op60, io_acc_block_signal_op79)
    begin
        if (((not(((icmp_ln56_fu_176_p2 = ap_const_lv1_0) and (io_acc_block_signal_op25 = ap_const_logic_0))) and (icmp_ln56_fu_176_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)) or (not((((icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (io_acc_block_signal_op51 = ap_const_logic_0)) or ((icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (io_acc_block_signal_op46 = ap_const_logic_0)))) and (icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4)) or (not(((icmp_ln74_fu_256_p2 = ap_const_lv1_0) and (io_acc_block_signal_op79 = ap_const_logic_0))) and (icmp_ln74_fu_256_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7)) or (not(((icmp_ln68_fu_232_p2 = ap_const_lv1_0) and (io_acc_block_signal_op60 = ap_const_logic_0))) and (icmp_ln68_fu_232_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5)) or (not(((icmp_ln61_fu_188_p2 = ap_const_lv1_0) and (io_acc_block_signal_op37 = ap_const_logic_0))) and (icmp_ln61_fu_188_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            res_V_data_1_V_write <= ap_const_logic_1;
        else 
            res_V_data_1_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_2_V_blk_n_assign_proc : process(res_V_data_2_V_full_n, ap_CS_fsm_state4, icmp_ln65_fu_200_p2, ap_CS_fsm_state2, icmp_ln56_fu_176_p2, ap_CS_fsm_state3, icmp_ln61_fu_188_p2, ap_CS_fsm_state5, icmp_ln68_fu_232_p2, ap_CS_fsm_state7, icmp_ln74_fu_256_p2)
    begin
        if ((((icmp_ln56_fu_176_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((icmp_ln74_fu_256_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7)) or ((icmp_ln68_fu_232_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((icmp_ln61_fu_188_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            res_V_data_2_V_blk_n <= res_V_data_2_V_full_n;
        else 
            res_V_data_2_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    res_V_data_2_V_din_assign_proc : process(data_V_data_2_V_dout, ap_CS_fsm_state4, icmp_ln65_fu_200_p2, ap_CS_fsm_state2, icmp_ln56_fu_176_p2, ap_CS_fsm_state3, icmp_ln61_fu_188_p2, ap_CS_fsm_state5, icmp_ln68_fu_232_p2, ap_CS_fsm_state7, icmp_ln74_fu_256_p2, io_acc_block_signal_op25, io_acc_block_signal_op37, io_acc_block_signal_op46, io_acc_block_signal_op51, io_acc_block_signal_op60, io_acc_block_signal_op79)
    begin
        if ((not((((icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (io_acc_block_signal_op51 = ap_const_logic_0)) or ((icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (io_acc_block_signal_op46 = ap_const_logic_0)))) and (icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            res_V_data_2_V_din <= data_V_data_2_V_dout;
        elsif (((not(((icmp_ln56_fu_176_p2 = ap_const_lv1_0) and (io_acc_block_signal_op25 = ap_const_logic_0))) and (icmp_ln56_fu_176_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)) or (not(((icmp_ln74_fu_256_p2 = ap_const_lv1_0) and (io_acc_block_signal_op79 = ap_const_logic_0))) and (icmp_ln74_fu_256_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7)) or (not(((icmp_ln68_fu_232_p2 = ap_const_lv1_0) and (io_acc_block_signal_op60 = ap_const_logic_0))) and (icmp_ln68_fu_232_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5)) or (not(((icmp_ln61_fu_188_p2 = ap_const_lv1_0) and (io_acc_block_signal_op37 = ap_const_logic_0))) and (icmp_ln61_fu_188_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            res_V_data_2_V_din <= ap_const_lv8_0;
        else 
            res_V_data_2_V_din <= "XXXXXXXX";
        end if; 
    end process;


    res_V_data_2_V_write_assign_proc : process(ap_CS_fsm_state4, icmp_ln65_fu_200_p2, ap_CS_fsm_state2, icmp_ln56_fu_176_p2, ap_CS_fsm_state3, icmp_ln61_fu_188_p2, ap_CS_fsm_state5, icmp_ln68_fu_232_p2, ap_CS_fsm_state7, icmp_ln74_fu_256_p2, io_acc_block_signal_op25, io_acc_block_signal_op37, io_acc_block_signal_op46, io_acc_block_signal_op51, io_acc_block_signal_op60, io_acc_block_signal_op79)
    begin
        if (((not(((icmp_ln56_fu_176_p2 = ap_const_lv1_0) and (io_acc_block_signal_op25 = ap_const_logic_0))) and (icmp_ln56_fu_176_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)) or (not((((icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (io_acc_block_signal_op51 = ap_const_logic_0)) or ((icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (io_acc_block_signal_op46 = ap_const_logic_0)))) and (icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4)) or (not(((icmp_ln74_fu_256_p2 = ap_const_lv1_0) and (io_acc_block_signal_op79 = ap_const_logic_0))) and (icmp_ln74_fu_256_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7)) or (not(((icmp_ln68_fu_232_p2 = ap_const_lv1_0) and (io_acc_block_signal_op60 = ap_const_logic_0))) and (icmp_ln68_fu_232_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5)) or (not(((icmp_ln61_fu_188_p2 = ap_const_lv1_0) and (io_acc_block_signal_op37 = ap_const_logic_0))) and (icmp_ln61_fu_188_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            res_V_data_2_V_write <= ap_const_logic_1;
        else 
            res_V_data_2_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_3_V_blk_n_assign_proc : process(res_V_data_3_V_full_n, ap_CS_fsm_state4, icmp_ln65_fu_200_p2, ap_CS_fsm_state2, icmp_ln56_fu_176_p2, ap_CS_fsm_state3, icmp_ln61_fu_188_p2, ap_CS_fsm_state5, icmp_ln68_fu_232_p2, ap_CS_fsm_state7, icmp_ln74_fu_256_p2)
    begin
        if ((((icmp_ln56_fu_176_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((icmp_ln74_fu_256_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7)) or ((icmp_ln68_fu_232_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((icmp_ln61_fu_188_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            res_V_data_3_V_blk_n <= res_V_data_3_V_full_n;
        else 
            res_V_data_3_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    res_V_data_3_V_din_assign_proc : process(data_V_data_3_V_dout, ap_CS_fsm_state4, icmp_ln65_fu_200_p2, ap_CS_fsm_state2, icmp_ln56_fu_176_p2, ap_CS_fsm_state3, icmp_ln61_fu_188_p2, ap_CS_fsm_state5, icmp_ln68_fu_232_p2, ap_CS_fsm_state7, icmp_ln74_fu_256_p2, io_acc_block_signal_op25, io_acc_block_signal_op37, io_acc_block_signal_op46, io_acc_block_signal_op51, io_acc_block_signal_op60, io_acc_block_signal_op79)
    begin
        if ((not((((icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (io_acc_block_signal_op51 = ap_const_logic_0)) or ((icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (io_acc_block_signal_op46 = ap_const_logic_0)))) and (icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            res_V_data_3_V_din <= data_V_data_3_V_dout;
        elsif (((not(((icmp_ln56_fu_176_p2 = ap_const_lv1_0) and (io_acc_block_signal_op25 = ap_const_logic_0))) and (icmp_ln56_fu_176_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)) or (not(((icmp_ln74_fu_256_p2 = ap_const_lv1_0) and (io_acc_block_signal_op79 = ap_const_logic_0))) and (icmp_ln74_fu_256_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7)) or (not(((icmp_ln68_fu_232_p2 = ap_const_lv1_0) and (io_acc_block_signal_op60 = ap_const_logic_0))) and (icmp_ln68_fu_232_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5)) or (not(((icmp_ln61_fu_188_p2 = ap_const_lv1_0) and (io_acc_block_signal_op37 = ap_const_logic_0))) and (icmp_ln61_fu_188_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            res_V_data_3_V_din <= ap_const_lv8_0;
        else 
            res_V_data_3_V_din <= "XXXXXXXX";
        end if; 
    end process;


    res_V_data_3_V_write_assign_proc : process(ap_CS_fsm_state4, icmp_ln65_fu_200_p2, ap_CS_fsm_state2, icmp_ln56_fu_176_p2, ap_CS_fsm_state3, icmp_ln61_fu_188_p2, ap_CS_fsm_state5, icmp_ln68_fu_232_p2, ap_CS_fsm_state7, icmp_ln74_fu_256_p2, io_acc_block_signal_op25, io_acc_block_signal_op37, io_acc_block_signal_op46, io_acc_block_signal_op51, io_acc_block_signal_op60, io_acc_block_signal_op79)
    begin
        if (((not(((icmp_ln56_fu_176_p2 = ap_const_lv1_0) and (io_acc_block_signal_op25 = ap_const_logic_0))) and (icmp_ln56_fu_176_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)) or (not((((icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (io_acc_block_signal_op51 = ap_const_logic_0)) or ((icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (io_acc_block_signal_op46 = ap_const_logic_0)))) and (icmp_ln65_fu_200_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4)) or (not(((icmp_ln74_fu_256_p2 = ap_const_lv1_0) and (io_acc_block_signal_op79 = ap_const_logic_0))) and (icmp_ln74_fu_256_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7)) or (not(((icmp_ln68_fu_232_p2 = ap_const_lv1_0) and (io_acc_block_signal_op60 = ap_const_logic_0))) and (icmp_ln68_fu_232_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5)) or (not(((icmp_ln61_fu_188_p2 = ap_const_lv1_0) and (io_acc_block_signal_op37 = ap_const_logic_0))) and (icmp_ln61_fu_188_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            res_V_data_3_V_write <= ap_const_logic_1;
        else 
            res_V_data_3_V_write <= ap_const_logic_0;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
