AcceleratorConfig:
  Driver: python
  Interface: axi_stream
  Precision:
    Input: float
    Output: float
Backend: VivadoAccelerator
Board: pynq-z2
ClockPeriod: 10
HLSConfig:
  LayerName:
    flatten:
      StreamDepth: 10000
    in_local:
      StreamDepth: 10000
    input_1:
      Precision: ap_ufixed<8,0>
      ReuseFactor: 16384
      StreamDepth: 10000
      Trace: false
    out_local:
      StreamDepth: 10000
    q_activation:
      Precision:
        default: ap_fixed<9,6>
        result: ap_fixed<8,3,AP_RND,AP_SAT>
      ReuseFactor: 16384
      StreamDepth: 10000
      Trace: false
    q_activation_1:
      Precision:
        default: ap_fixed<9,6>
        result: ap_fixed<8,3,AP_RND,AP_SAT>
      ReuseFactor: 16384
      StreamDepth: 10000
      Trace: false
    q_activation_2:
      Precision:
        default: ap_fixed<9,6>
        result: ap_fixed<8,3,AP_RND,AP_SAT>
      ReuseFactor: 16384
      StreamDepth: 10000
      Trace: false
    q_activation_3:
      Precision:
        default: ap_fixed<9,6>
        result: ap_fixed<8,3,AP_RND,AP_SAT>
      ReuseFactor: 16384
      StreamDepth: 10000
      Trace: false
    q_activation_4:
      Precision:
        default: ap_fixed<9,6>
        result: ap_fixed<8,3,AP_RND,AP_SAT>
    q_activation_5:
      Precision: ap_fixed<8,6>
      ReuseFactor: 16384
      StreamDepth: 10000
      Trace: false
    q_conv2d_batchnorm:
      ConvImplementation: LineBuffer
      Precision:
        bias: ap_fixed<8,3>
        default: ap_fixed<9,6>
        result: ap_fixed<9,6>
        weight: ap_fixed<8,3>
      ReuseFactor: 16384
      StreamDepth: 10000
      Trace: false
      accum_t: ap_fixed<14,6>
    q_conv2d_batchnorm_1:
      ConvImplementation: LineBuffer
      Precision:
        bias: ap_fixed<8,3>
        default: ap_fixed<9,6>
        result: ap_fixed<9,6>
        weight: ap_fixed<8,3>
      ReuseFactor: 16384
      StreamDepth: 10000
      Trace: false
      accum_t: ap_fixed<14,6>
    q_conv2d_batchnorm_1_linear:
      Precision:
        default: ap_fixed<9,6>
        result: ap_fixed<9,6>
    q_conv2d_batchnorm_2:
      ConvImplementation: LineBuffer
      Precision:
        bias: ap_fixed<8,3>
        default: ap_fixed<9,6>
        result: ap_fixed<9,6>
        weight: ap_fixed<8,3>
      ReuseFactor: 16384
      StreamDepth: 10000
      Trace: false
      accum_t: ap_fixed<14,6>
    q_conv2d_batchnorm_2_linear:
      Precision:
        default: ap_fixed<9,6>
        result: ap_fixed<9,6>
    q_conv2d_batchnorm_3:
      ConvImplementation: LineBuffer
      Precision:
        bias: ap_fixed<8,3>
        default: ap_fixed<9,6>
        result: ap_fixed<9,6>
        weight: ap_fixed<8,3>
      ReuseFactor: 16384
      StreamDepth: 10000
      Trace: false
      accum_t: ap_fixed<14,6>
    q_conv2d_batchnorm_3_linear:
      Precision:
        default: ap_fixed<9,6>
        result: ap_fixed<9,6>
    q_conv2d_batchnorm_4:
      ConvImplementation: LineBuffer
      Precision:
        bias: ap_fixed<8,3>
        default: ap_fixed<9,6>
        result: ap_fixed<9,6>
        weight: ap_fixed<8,3>
      ReuseFactor: 16384
      StreamDepth: 10000
      Trace: false
      accum_t: ap_fixed<14,6>
    q_conv2d_batchnorm_4_linear:
      Precision:
        default: ap_fixed<9,6>
        result: ap_fixed<9,6>
    q_conv2d_batchnorm_linear:
      Precision:
        default: ap_fixed<9,6>
        result: ap_fixed<9,6>
    q_dense:
      Precision:
        bias: ap_fixed<8,3>
        default: ap_fixed<8,6>
        result: ap_fixed<8,6>
        weight: ap_fixed<8,3>
      ReuseFactor: 16384
      StreamDepth: 10000
      Trace: false
      accum_t: ap_fixed<12,6>
    zp2d_q_conv2d_batchnorm_1:
      StreamDepth: 10000
    zp2d_q_conv2d_batchnorm_2:
      StreamDepth: 10000
    zp2d_q_conv2d_batchnorm_3:
      StreamDepth: 10000
    zp2d_q_conv2d_batchnorm_4:
      StreamDepth: 10000
  Model:
    FIFO_opt: 1
    Precision: ap_fixed<8,6>
    ReuseFactor: 16384
    Strategy: Resource
  SkipOptimizers:
  - reshape_stream
IOType: io_stream
InputData: resnet_v1_eembc_quantized_tiny2/X_test.npy
KerasModel: !keras_model 'my-hls-test-quantized-tiny2/keras_model.h5'
OutputDir: my-hls-test-quantized-tiny2
OutputPredictions: resnet_v1_eembc_quantized_tiny2/y_test.npy
ProjectName: myproject
Stamp: 91b5812e
XilinxPart: xc7z020clg400-1
