// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module zeropad2d_cl_array_array_ap_fixed_4u_config21_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        data_V_data_0_V_dout,
        data_V_data_0_V_empty_n,
        data_V_data_0_V_read,
        data_V_data_1_V_dout,
        data_V_data_1_V_empty_n,
        data_V_data_1_V_read,
        data_V_data_2_V_dout,
        data_V_data_2_V_empty_n,
        data_V_data_2_V_read,
        data_V_data_3_V_dout,
        data_V_data_3_V_empty_n,
        data_V_data_3_V_read,
        res_V_data_0_V_din,
        res_V_data_0_V_full_n,
        res_V_data_0_V_write,
        res_V_data_1_V_din,
        res_V_data_1_V_full_n,
        res_V_data_1_V_write,
        res_V_data_2_V_din,
        res_V_data_2_V_full_n,
        res_V_data_2_V_write,
        res_V_data_3_V_din,
        res_V_data_3_V_full_n,
        res_V_data_3_V_write
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_state6 = 7'd32;
parameter    ap_ST_fsm_state7 = 7'd64;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [7:0] data_V_data_0_V_dout;
input   data_V_data_0_V_empty_n;
output   data_V_data_0_V_read;
input  [7:0] data_V_data_1_V_dout;
input   data_V_data_1_V_empty_n;
output   data_V_data_1_V_read;
input  [7:0] data_V_data_2_V_dout;
input   data_V_data_2_V_empty_n;
output   data_V_data_2_V_read;
input  [7:0] data_V_data_3_V_dout;
input   data_V_data_3_V_empty_n;
output   data_V_data_3_V_read;
output  [7:0] res_V_data_0_V_din;
input   res_V_data_0_V_full_n;
output   res_V_data_0_V_write;
output  [7:0] res_V_data_1_V_din;
input   res_V_data_1_V_full_n;
output   res_V_data_1_V_write;
output  [7:0] res_V_data_2_V_din;
input   res_V_data_2_V_full_n;
output   res_V_data_2_V_write;
output  [7:0] res_V_data_3_V_din;
input   res_V_data_3_V_full_n;
output   res_V_data_3_V_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg data_V_data_0_V_read;
reg data_V_data_1_V_read;
reg data_V_data_2_V_read;
reg data_V_data_3_V_read;
reg[7:0] res_V_data_0_V_din;
reg res_V_data_0_V_write;
reg[7:0] res_V_data_1_V_din;
reg res_V_data_1_V_write;
reg[7:0] res_V_data_2_V_din;
reg res_V_data_2_V_write;
reg[7:0] res_V_data_3_V_din;
reg res_V_data_3_V_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    data_V_data_0_V_blk_n;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln65_fu_200_p2;
reg    data_V_data_1_V_blk_n;
reg    data_V_data_2_V_blk_n;
reg    data_V_data_3_V_blk_n;
reg    res_V_data_0_V_blk_n;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln56_fu_176_p2;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln61_fu_188_p2;
wire    ap_CS_fsm_state5;
wire   [0:0] icmp_ln68_fu_232_p2;
wire    ap_CS_fsm_state7;
wire   [0:0] icmp_ln74_fu_256_p2;
reg    res_V_data_1_V_blk_n;
reg    res_V_data_2_V_blk_n;
reg    res_V_data_3_V_blk_n;
wire   [5:0] j_fu_182_p2;
wire    io_acc_block_signal_op25;
reg    ap_block_state2;
wire   [5:0] i_1_fu_194_p2;
reg   [5:0] i_1_reg_279;
wire    io_acc_block_signal_op37;
reg    ap_block_state3;
wire   [5:0] j_1_fu_206_p2;
wire    io_acc_block_signal_op46;
wire    io_acc_block_signal_op51;
reg    ap_block_state4;
wire   [1:0] j_3_fu_238_p2;
wire    io_acc_block_signal_op60;
reg    ap_block_state5;
wire   [1:0] i_fu_250_p2;
reg   [1:0] i_reg_303;
wire    ap_CS_fsm_state6;
wire   [5:0] j_2_fu_262_p2;
wire    io_acc_block_signal_op79;
reg    ap_block_state7;
reg   [5:0] j_0_reg_110;
reg    ap_block_state1;
reg   [5:0] i1_0_reg_121;
reg   [5:0] j3_0_reg_132;
reg   [1:0] j4_0_reg_143;
reg   [1:0] i5_0_reg_154;
reg   [5:0] j6_0_reg_165;
wire   [0:0] icmp_ln73_fu_244_p2;
reg   [6:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 7'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln73_fu_244_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((icmp_ln56_fu_176_p2 == 1'd0) & (io_acc_block_signal_op25 == 1'b0)) & (icmp_ln56_fu_176_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        i1_0_reg_121 <= 6'd0;
    end else if ((~((icmp_ln68_fu_232_p2 == 1'd0) & (io_acc_block_signal_op60 == 1'b0)) & (1'b1 == ap_CS_fsm_state5) & (icmp_ln68_fu_232_p2 == 1'd1))) begin
        i1_0_reg_121 <= i_1_reg_279;
    end
end

always @ (posedge ap_clk) begin
    if ((~((icmp_ln61_fu_188_p2 == 1'd0) & (io_acc_block_signal_op37 == 1'b0)) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln61_fu_188_p2 == 1'd1))) begin
        i5_0_reg_154 <= 2'd0;
    end else if ((~((icmp_ln74_fu_256_p2 == 1'd0) & (io_acc_block_signal_op79 == 1'b0)) & (1'b1 == ap_CS_fsm_state7) & (icmp_ln74_fu_256_p2 == 1'd1))) begin
        i5_0_reg_154 <= i_reg_303;
    end
end

always @ (posedge ap_clk) begin
    if ((~((icmp_ln61_fu_188_p2 == 1'd0) & (io_acc_block_signal_op37 == 1'b0)) & (icmp_ln61_fu_188_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        j3_0_reg_132 <= 6'd0;
    end else if ((~(((icmp_ln65_fu_200_p2 == 1'd0) & (io_acc_block_signal_op51 == 1'b0)) | ((icmp_ln65_fu_200_p2 == 1'd0) & (io_acc_block_signal_op46 == 1'b0))) & (icmp_ln65_fu_200_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        j3_0_reg_132 <= j_1_fu_206_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((icmp_ln65_fu_200_p2 == 1'd0) & (io_acc_block_signal_op51 == 1'b0)) | ((icmp_ln65_fu_200_p2 == 1'd0) & (io_acc_block_signal_op46 == 1'b0))) & (icmp_ln65_fu_200_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        j4_0_reg_143 <= 2'd0;
    end else if ((~((icmp_ln68_fu_232_p2 == 1'd0) & (io_acc_block_signal_op60 == 1'b0)) & (icmp_ln68_fu_232_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        j4_0_reg_143 <= j_3_fu_238_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((icmp_ln74_fu_256_p2 == 1'd0) & (io_acc_block_signal_op79 == 1'b0)) & (icmp_ln74_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        j6_0_reg_165 <= j_2_fu_262_p2;
    end else if (((icmp_ln73_fu_244_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        j6_0_reg_165 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((icmp_ln56_fu_176_p2 == 1'd0) & (io_acc_block_signal_op25 == 1'b0)) & (icmp_ln56_fu_176_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        j_0_reg_110 <= j_fu_182_p2;
    end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        j_0_reg_110 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((icmp_ln61_fu_188_p2 == 1'd0) & (io_acc_block_signal_op37 == 1'b0)) & (1'b1 == ap_CS_fsm_state3))) begin
        i_1_reg_279 <= i_1_fu_194_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        i_reg_303 <= i_fu_250_p2;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln73_fu_244_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln65_fu_200_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        data_V_data_0_V_blk_n = data_V_data_0_V_empty_n;
    end else begin
        data_V_data_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((icmp_ln65_fu_200_p2 == 1'd0) & (io_acc_block_signal_op51 == 1'b0)) | ((icmp_ln65_fu_200_p2 == 1'd0) & (io_acc_block_signal_op46 == 1'b0))) & (icmp_ln65_fu_200_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        data_V_data_0_V_read = 1'b1;
    end else begin
        data_V_data_0_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln65_fu_200_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        data_V_data_1_V_blk_n = data_V_data_1_V_empty_n;
    end else begin
        data_V_data_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((icmp_ln65_fu_200_p2 == 1'd0) & (io_acc_block_signal_op51 == 1'b0)) | ((icmp_ln65_fu_200_p2 == 1'd0) & (io_acc_block_signal_op46 == 1'b0))) & (icmp_ln65_fu_200_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        data_V_data_1_V_read = 1'b1;
    end else begin
        data_V_data_1_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln65_fu_200_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        data_V_data_2_V_blk_n = data_V_data_2_V_empty_n;
    end else begin
        data_V_data_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((icmp_ln65_fu_200_p2 == 1'd0) & (io_acc_block_signal_op51 == 1'b0)) | ((icmp_ln65_fu_200_p2 == 1'd0) & (io_acc_block_signal_op46 == 1'b0))) & (icmp_ln65_fu_200_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        data_V_data_2_V_read = 1'b1;
    end else begin
        data_V_data_2_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln65_fu_200_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        data_V_data_3_V_blk_n = data_V_data_3_V_empty_n;
    end else begin
        data_V_data_3_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((icmp_ln65_fu_200_p2 == 1'd0) & (io_acc_block_signal_op51 == 1'b0)) | ((icmp_ln65_fu_200_p2 == 1'd0) & (io_acc_block_signal_op46 == 1'b0))) & (icmp_ln65_fu_200_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        data_V_data_3_V_read = 1'b1;
    end else begin
        data_V_data_3_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln73_fu_244_p2 == 1'd1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if ((((icmp_ln56_fu_176_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln65_fu_200_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4)) | ((icmp_ln74_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)) | ((icmp_ln68_fu_232_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln61_fu_188_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        res_V_data_0_V_blk_n = res_V_data_0_V_full_n;
    end else begin
        res_V_data_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((icmp_ln65_fu_200_p2 == 1'd0) & (io_acc_block_signal_op51 == 1'b0)) | ((icmp_ln65_fu_200_p2 == 1'd0) & (io_acc_block_signal_op46 == 1'b0))) & (icmp_ln65_fu_200_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        res_V_data_0_V_din = data_V_data_0_V_dout;
    end else if (((~((icmp_ln56_fu_176_p2 == 1'd0) & (io_acc_block_signal_op25 == 1'b0)) & (icmp_ln56_fu_176_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | (~((icmp_ln74_fu_256_p2 == 1'd0) & (io_acc_block_signal_op79 == 1'b0)) & (icmp_ln74_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)) | (~((icmp_ln68_fu_232_p2 == 1'd0) & (io_acc_block_signal_op60 == 1'b0)) & (icmp_ln68_fu_232_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)) | (~((icmp_ln61_fu_188_p2 == 1'd0) & (io_acc_block_signal_op37 == 1'b0)) & (icmp_ln61_fu_188_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        res_V_data_0_V_din = 8'd0;
    end else begin
        res_V_data_0_V_din = 'bx;
    end
end

always @ (*) begin
    if (((~((icmp_ln56_fu_176_p2 == 1'd0) & (io_acc_block_signal_op25 == 1'b0)) & (icmp_ln56_fu_176_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | (~(((icmp_ln65_fu_200_p2 == 1'd0) & (io_acc_block_signal_op51 == 1'b0)) | ((icmp_ln65_fu_200_p2 == 1'd0) & (io_acc_block_signal_op46 == 1'b0))) & (icmp_ln65_fu_200_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4)) | (~((icmp_ln74_fu_256_p2 == 1'd0) & (io_acc_block_signal_op79 == 1'b0)) & (icmp_ln74_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)) | (~((icmp_ln68_fu_232_p2 == 1'd0) & (io_acc_block_signal_op60 == 1'b0)) & (icmp_ln68_fu_232_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)) | (~((icmp_ln61_fu_188_p2 == 1'd0) & (io_acc_block_signal_op37 == 1'b0)) & (icmp_ln61_fu_188_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        res_V_data_0_V_write = 1'b1;
    end else begin
        res_V_data_0_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln56_fu_176_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln65_fu_200_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4)) | ((icmp_ln74_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)) | ((icmp_ln68_fu_232_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln61_fu_188_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        res_V_data_1_V_blk_n = res_V_data_1_V_full_n;
    end else begin
        res_V_data_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((icmp_ln65_fu_200_p2 == 1'd0) & (io_acc_block_signal_op51 == 1'b0)) | ((icmp_ln65_fu_200_p2 == 1'd0) & (io_acc_block_signal_op46 == 1'b0))) & (icmp_ln65_fu_200_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        res_V_data_1_V_din = data_V_data_1_V_dout;
    end else if (((~((icmp_ln56_fu_176_p2 == 1'd0) & (io_acc_block_signal_op25 == 1'b0)) & (icmp_ln56_fu_176_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | (~((icmp_ln74_fu_256_p2 == 1'd0) & (io_acc_block_signal_op79 == 1'b0)) & (icmp_ln74_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)) | (~((icmp_ln68_fu_232_p2 == 1'd0) & (io_acc_block_signal_op60 == 1'b0)) & (icmp_ln68_fu_232_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)) | (~((icmp_ln61_fu_188_p2 == 1'd0) & (io_acc_block_signal_op37 == 1'b0)) & (icmp_ln61_fu_188_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        res_V_data_1_V_din = 8'd0;
    end else begin
        res_V_data_1_V_din = 'bx;
    end
end

always @ (*) begin
    if (((~((icmp_ln56_fu_176_p2 == 1'd0) & (io_acc_block_signal_op25 == 1'b0)) & (icmp_ln56_fu_176_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | (~(((icmp_ln65_fu_200_p2 == 1'd0) & (io_acc_block_signal_op51 == 1'b0)) | ((icmp_ln65_fu_200_p2 == 1'd0) & (io_acc_block_signal_op46 == 1'b0))) & (icmp_ln65_fu_200_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4)) | (~((icmp_ln74_fu_256_p2 == 1'd0) & (io_acc_block_signal_op79 == 1'b0)) & (icmp_ln74_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)) | (~((icmp_ln68_fu_232_p2 == 1'd0) & (io_acc_block_signal_op60 == 1'b0)) & (icmp_ln68_fu_232_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)) | (~((icmp_ln61_fu_188_p2 == 1'd0) & (io_acc_block_signal_op37 == 1'b0)) & (icmp_ln61_fu_188_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        res_V_data_1_V_write = 1'b1;
    end else begin
        res_V_data_1_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln56_fu_176_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln65_fu_200_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4)) | ((icmp_ln74_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)) | ((icmp_ln68_fu_232_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln61_fu_188_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        res_V_data_2_V_blk_n = res_V_data_2_V_full_n;
    end else begin
        res_V_data_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((icmp_ln65_fu_200_p2 == 1'd0) & (io_acc_block_signal_op51 == 1'b0)) | ((icmp_ln65_fu_200_p2 == 1'd0) & (io_acc_block_signal_op46 == 1'b0))) & (icmp_ln65_fu_200_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        res_V_data_2_V_din = data_V_data_2_V_dout;
    end else if (((~((icmp_ln56_fu_176_p2 == 1'd0) & (io_acc_block_signal_op25 == 1'b0)) & (icmp_ln56_fu_176_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | (~((icmp_ln74_fu_256_p2 == 1'd0) & (io_acc_block_signal_op79 == 1'b0)) & (icmp_ln74_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)) | (~((icmp_ln68_fu_232_p2 == 1'd0) & (io_acc_block_signal_op60 == 1'b0)) & (icmp_ln68_fu_232_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)) | (~((icmp_ln61_fu_188_p2 == 1'd0) & (io_acc_block_signal_op37 == 1'b0)) & (icmp_ln61_fu_188_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        res_V_data_2_V_din = 8'd0;
    end else begin
        res_V_data_2_V_din = 'bx;
    end
end

always @ (*) begin
    if (((~((icmp_ln56_fu_176_p2 == 1'd0) & (io_acc_block_signal_op25 == 1'b0)) & (icmp_ln56_fu_176_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | (~(((icmp_ln65_fu_200_p2 == 1'd0) & (io_acc_block_signal_op51 == 1'b0)) | ((icmp_ln65_fu_200_p2 == 1'd0) & (io_acc_block_signal_op46 == 1'b0))) & (icmp_ln65_fu_200_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4)) | (~((icmp_ln74_fu_256_p2 == 1'd0) & (io_acc_block_signal_op79 == 1'b0)) & (icmp_ln74_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)) | (~((icmp_ln68_fu_232_p2 == 1'd0) & (io_acc_block_signal_op60 == 1'b0)) & (icmp_ln68_fu_232_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)) | (~((icmp_ln61_fu_188_p2 == 1'd0) & (io_acc_block_signal_op37 == 1'b0)) & (icmp_ln61_fu_188_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        res_V_data_2_V_write = 1'b1;
    end else begin
        res_V_data_2_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln56_fu_176_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln65_fu_200_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4)) | ((icmp_ln74_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)) | ((icmp_ln68_fu_232_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln61_fu_188_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        res_V_data_3_V_blk_n = res_V_data_3_V_full_n;
    end else begin
        res_V_data_3_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((icmp_ln65_fu_200_p2 == 1'd0) & (io_acc_block_signal_op51 == 1'b0)) | ((icmp_ln65_fu_200_p2 == 1'd0) & (io_acc_block_signal_op46 == 1'b0))) & (icmp_ln65_fu_200_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        res_V_data_3_V_din = data_V_data_3_V_dout;
    end else if (((~((icmp_ln56_fu_176_p2 == 1'd0) & (io_acc_block_signal_op25 == 1'b0)) & (icmp_ln56_fu_176_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | (~((icmp_ln74_fu_256_p2 == 1'd0) & (io_acc_block_signal_op79 == 1'b0)) & (icmp_ln74_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)) | (~((icmp_ln68_fu_232_p2 == 1'd0) & (io_acc_block_signal_op60 == 1'b0)) & (icmp_ln68_fu_232_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)) | (~((icmp_ln61_fu_188_p2 == 1'd0) & (io_acc_block_signal_op37 == 1'b0)) & (icmp_ln61_fu_188_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        res_V_data_3_V_din = 8'd0;
    end else begin
        res_V_data_3_V_din = 'bx;
    end
end

always @ (*) begin
    if (((~((icmp_ln56_fu_176_p2 == 1'd0) & (io_acc_block_signal_op25 == 1'b0)) & (icmp_ln56_fu_176_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | (~(((icmp_ln65_fu_200_p2 == 1'd0) & (io_acc_block_signal_op51 == 1'b0)) | ((icmp_ln65_fu_200_p2 == 1'd0) & (io_acc_block_signal_op46 == 1'b0))) & (icmp_ln65_fu_200_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4)) | (~((icmp_ln74_fu_256_p2 == 1'd0) & (io_acc_block_signal_op79 == 1'b0)) & (icmp_ln74_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)) | (~((icmp_ln68_fu_232_p2 == 1'd0) & (io_acc_block_signal_op60 == 1'b0)) & (icmp_ln68_fu_232_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)) | (~((icmp_ln61_fu_188_p2 == 1'd0) & (io_acc_block_signal_op37 == 1'b0)) & (icmp_ln61_fu_188_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        res_V_data_3_V_write = 1'b1;
    end else begin
        res_V_data_3_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((~((icmp_ln56_fu_176_p2 == 1'd0) & (io_acc_block_signal_op25 == 1'b0)) & (icmp_ln56_fu_176_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else if ((~((icmp_ln56_fu_176_p2 == 1'd0) & (io_acc_block_signal_op25 == 1'b0)) & (icmp_ln56_fu_176_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if ((~((icmp_ln61_fu_188_p2 == 1'd0) & (io_acc_block_signal_op37 == 1'b0)) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln61_fu_188_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else if ((~((icmp_ln61_fu_188_p2 == 1'd0) & (io_acc_block_signal_op37 == 1'b0)) & (icmp_ln61_fu_188_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if ((~(((icmp_ln65_fu_200_p2 == 1'd0) & (io_acc_block_signal_op51 == 1'b0)) | ((icmp_ln65_fu_200_p2 == 1'd0) & (io_acc_block_signal_op46 == 1'b0))) & (icmp_ln65_fu_200_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else if ((~(((icmp_ln65_fu_200_p2 == 1'd0) & (io_acc_block_signal_op51 == 1'b0)) | ((icmp_ln65_fu_200_p2 == 1'd0) & (io_acc_block_signal_op46 == 1'b0))) & (icmp_ln65_fu_200_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if ((~((icmp_ln68_fu_232_p2 == 1'd0) & (io_acc_block_signal_op60 == 1'b0)) & (1'b1 == ap_CS_fsm_state5) & (icmp_ln68_fu_232_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else if ((~((icmp_ln68_fu_232_p2 == 1'd0) & (io_acc_block_signal_op60 == 1'b0)) & (icmp_ln68_fu_232_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln73_fu_244_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            if ((~((icmp_ln74_fu_256_p2 == 1'd0) & (io_acc_block_signal_op79 == 1'b0)) & (1'b1 == ap_CS_fsm_state7) & (icmp_ln74_fu_256_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else if ((~((icmp_ln74_fu_256_p2 == 1'd0) & (io_acc_block_signal_op79 == 1'b0)) & (icmp_ln74_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2 = ((icmp_ln56_fu_176_p2 == 1'd0) & (io_acc_block_signal_op25 == 1'b0));
end

always @ (*) begin
    ap_block_state3 = ((icmp_ln61_fu_188_p2 == 1'd0) & (io_acc_block_signal_op37 == 1'b0));
end

always @ (*) begin
    ap_block_state4 = (((icmp_ln65_fu_200_p2 == 1'd0) & (io_acc_block_signal_op51 == 1'b0)) | ((icmp_ln65_fu_200_p2 == 1'd0) & (io_acc_block_signal_op46 == 1'b0)));
end

always @ (*) begin
    ap_block_state5 = ((icmp_ln68_fu_232_p2 == 1'd0) & (io_acc_block_signal_op60 == 1'b0));
end

always @ (*) begin
    ap_block_state7 = ((icmp_ln74_fu_256_p2 == 1'd0) & (io_acc_block_signal_op79 == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign i_1_fu_194_p2 = (i1_0_reg_121 + 6'd1);

assign i_fu_250_p2 = (i5_0_reg_154 + 2'd1);

assign icmp_ln56_fu_176_p2 = ((j_0_reg_110 == 6'd35) ? 1'b1 : 1'b0);

assign icmp_ln61_fu_188_p2 = ((i1_0_reg_121 == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln65_fu_200_p2 = ((j3_0_reg_132 == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln68_fu_232_p2 = ((j4_0_reg_143 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln73_fu_244_p2 = ((i5_0_reg_154 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln74_fu_256_p2 = ((j6_0_reg_165 == 6'd35) ? 1'b1 : 1'b0);

assign io_acc_block_signal_op25 = (res_V_data_3_V_full_n & res_V_data_2_V_full_n & res_V_data_1_V_full_n & res_V_data_0_V_full_n);

assign io_acc_block_signal_op37 = (res_V_data_3_V_full_n & res_V_data_2_V_full_n & res_V_data_1_V_full_n & res_V_data_0_V_full_n);

assign io_acc_block_signal_op46 = (data_V_data_3_V_empty_n & data_V_data_2_V_empty_n & data_V_data_1_V_empty_n & data_V_data_0_V_empty_n);

assign io_acc_block_signal_op51 = (res_V_data_3_V_full_n & res_V_data_2_V_full_n & res_V_data_1_V_full_n & res_V_data_0_V_full_n);

assign io_acc_block_signal_op60 = (res_V_data_3_V_full_n & res_V_data_2_V_full_n & res_V_data_1_V_full_n & res_V_data_0_V_full_n);

assign io_acc_block_signal_op79 = (res_V_data_3_V_full_n & res_V_data_2_V_full_n & res_V_data_1_V_full_n & res_V_data_0_V_full_n);

assign j_1_fu_206_p2 = (j3_0_reg_132 + 6'd1);

assign j_2_fu_262_p2 = (j6_0_reg_165 + 6'd1);

assign j_3_fu_238_p2 = (j4_0_reg_143 + 2'd1);

assign j_fu_182_p2 = (j_0_reg_110 + 6'd1);

assign start_out = real_start;

endmodule //zeropad2d_cl_array_array_ap_fixed_4u_config21_s
